import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'
import { ArrowUpCircleIcon } from '@heroicons/react/24/solid'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import requests from "../utils/requests"
// import { fetchPageInfo } from '../utils/fetchPageInfo'
// import { fetchExperiences } from '../utils/fetchExperiences'
// import { fetchSkills } from '../utils/fetchSkills'
// import { fetchProjects } from '../utils/fetchProjects'
// import { fetchSocials } from '../utils/fetchSocials'
// import styles from '../styles/Home.module.css'

interface Props  {
  pageInfo: PageInfo,
  experiences: Experience[]
  skills: Skill[]
  projects: Project[],
  socials: Social[]
}

const Home = ({ pageInfo, experiences, skills, projects, socials }: Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 appScrollbar">
      <Head>
        <title>Marvin`s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section>

      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>

      <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences} />
      </section>

      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>

      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>

      <section id="contact" className="snap-start">
        <ContactMe />
      </section>

    <Link href="#hero">
      <footer className="absolute z-10 bottom-5 right-2 md:right-8 lg:right-10">
        <ArrowUpCircleIcon className="text-right text-gray-400 bg-transparent rounded-full cursor-pointer w-14 h-14 filter grayscale hover:text-gray-50" />
       </footer>
    </Link>


    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<Props> = async() => {
  // const pageInfo: PageInfo =  await fetchPageInfo()
  // const experiences: Experience[] =  await fetchExperiences()
  // const skills: Skill[] =  await fetchSkills()
  // const projects: Project[] =  await fetchProjects()
  // const socials: Social[] =  await fetchSocials()

  const [
    pageInfo,
    experiences,
    skills,
    projects,
    socials,
  ] = await Promise.all([
    fetch(requests.fetchPageInf).then((res) => res.json()),
    fetch(requests.fetchExp).then((res) => res.json()),
    fetch(requests.fetchSkil).then((res) => res.json()),
    fetch(requests.fetchProj).then((res) => res.json()),
    fetch(requests.fetchSoci).then((res) => res.json())
  ])

  return {
    props: {
      pageInfo: pageInfo.pageInfo,
      experiences: experiences.experiences,
      skills: skills.skills,
      projects: projects.projects,
      socials: socials.socials,
      // pageInfo,
      // experiences,
      // skills,
      // projects,
      // socials,
    },
    // Next will try and regenerate the page after n time of seconds
    revalidate: 30
  }
}