name: Node.js CI

on:
  push:
    branches: 
      - main
      - develop
      
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env:
      ## Environment variable
      # NEXT_PUBLIC_SANITY_DATASET: ''

    strategy:
      matrix:
        node-version: [16.x]


        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn 
    - run: yarn run build
    # - run: yarn test
